import { Era } from '@/types'

export const ERAS: Era[] = [
  // JAPAN (7)
  {
    id: 'feudal-japan',
    name: 'Feudal Japan',
    year: '1185–1600',
    region: 'Japan',
    emoji: '⚔️',
    description: 'Warring samurai clans, honor codes, and the way of Bushido define an age of constant conflict and rigid hierarchy.',
  },
  {
    id: 'edo-japan',
    name: 'Edo Period Japan',
    year: '1603–1868',
    region: 'Japan',
    emoji: '🏯',
    description: 'Peace under Tokugawa rule: merchant culture blossoms, kabuki fills theaters, and ronin walk a world without war.',
  },
  {
    id: 'sengoku-japan',
    name: 'Sengoku Japan',
    year: '1467–1615',
    region: 'Japan',
    emoji: '🔥',
    description: 'The Warring States era — daimyo battle for supremacy, ninjas lurk in shadows, and Oda Nobunaga reshapes a broken realm.',
  },
  {
    id: 'heian-japan',
    name: 'Heian Court Japan',
    year: '794–1185',
    region: 'Japan',
    emoji: '🌸',
    description: 'Aristocratic refinement: poetry duels, imperial intrigue, and the world\'s first novel emerge from silken Kyoto courts.',
  },
  {
    id: 'meiji-japan',
    name: 'Meiji Restoration',
    year: '1868–1912',
    region: 'Japan',
    emoji: '🚂',
    description: 'Japan tears open its doors: samurai yield to factories, Western suits replace kimono, and an empire is born in decades.',
  },
  {
    id: 'nara-japan',
    name: 'Nara Period Japan',
    year: '710–794',
    region: 'Japan',
    emoji: '🦌',
    description: 'Buddhism reshapes Japan: grand temples rise, sacred deer roam the capital, and Chinese culture floods through eager courts.',
  },
  {
    id: 'kamakura-japan',
    name: 'Kamakura Shogunate',
    year: '1185–1333',
    region: 'Japan',
    emoji: '🗡️',
    description: 'Japan\'s first military government — samurai displace courtiers, Zen Buddhism spreads, and the Mongol fleet meets divine winds.',
  },

  // CHINA (9)
  {
    id: 'han-china',
    name: 'Han Dynasty China',
    year: '206 BC–220 AD',
    region: 'China',
    emoji: '🐉',
    description: 'The Silk Road opens, Confucianism becomes state doctrine, and China\'s golden age establishes the template for all dynasties to come.',
  },
  {
    id: 'tang-china',
    name: 'Tang Dynasty China',
    year: '618–907',
    region: 'China',
    emoji: '🏮',
    description: 'The cosmopolitan apex: Chang\'an pulses with merchants from fifty nations, female emperor Wu Zetian rewrites history, poetry reaches heaven.',
  },
  {
    id: 'ming-china',
    name: 'Ming Dynasty China',
    year: '1368–1644',
    region: 'China',
    emoji: '🏛️',
    description: 'The Great Wall rebuilt in stone, Zheng He sails to Africa, and the Forbidden City rises — China closed to the world, magnificent and proud.',
  },
  {
    id: 'qin-china',
    name: 'Qin Dynasty China',
    year: '221–206 BC',
    region: 'China',
    emoji: '⚱️',
    description: 'The First Emperor unifies China by conquest and terror: weights standardized, books burned, a terracotta army waits in darkness for eternity.',
  },
  {
    id: 'song-china',
    name: 'Song Dynasty China',
    year: '960–1279',
    region: 'China',
    emoji: '🎋',
    description: 'Gunpowder, printing, and the compass emerge; merchant cities thrive; painting reaches sublime heights while northern nomads circle.',
  },
  {
    id: 'warring-states-china',
    name: 'Warring States China',
    year: '475–221 BC',
    region: 'China',
    emoji: '⚔️',
    description: 'Seven kingdoms tear China apart while Sun Tzu writes on war, Confucius walks the roads, and a hundred philosophical schools bloom.',
  },
  {
    id: 'three-kingdoms-china',
    name: 'Three Kingdoms China',
    year: '220–280 AD',
    region: 'China',
    emoji: '🔴',
    description: 'Wei, Wu, Shu — three brilliant rivals split a dying empire. Cao Cao schemes, Liu Bei rallies virtue, and Zhuge Liang defies fate.',
  },
  {
    id: 'yuan-china',
    name: 'Yuan Dynasty China',
    year: '1271–1368',
    region: 'China',
    emoji: '🏹',
    description: 'Kublai Khan rules from Beijing: Marco Polo stares wide-eyed, trade flows coast to coast, and Mongol horsemen govern a conquered world.',
  },
  {
    id: 'zhou-china',
    name: 'Zhou Dynasty China',
    year: '1046–256 BC',
    region: 'China',
    emoji: '☯️',
    description: 'Taoism, Confucianism, and Legalism born as feudal lords fracture the Zhou mandate — philosophy blooms from the ruins of certainty.',
  },

  // ROME & GREECE (9)
  {
    id: 'roman-republic',
    name: 'Roman Republic',
    year: '509–27 BC',
    region: 'Rome',
    emoji: '🏛️',
    description: 'Senators conspire on the steps of power: Caesar rises, Cicero thunders, Spartacus bleeds — the Republic tears itself apart on ambition.',
  },
  {
    id: 'roman-empire',
    name: 'Roman Empire',
    year: '27 BC–476 AD',
    region: 'Rome',
    emoji: '🦅',
    description: 'Augustus brings peace, Nero burns the city, gladiators die for bread and circuses — an empire that swallowed the world begins to crack.',
  },
  {
    id: 'fall-of-rome',
    name: 'Fall of Western Rome',
    year: '376–476 AD',
    region: 'Rome',
    emoji: '💀',
    description: 'Visigoths at the gates, coinage worthless, legions unpaid — the eternal city falls not with a bang but a long, terrible sigh.',
  },
  {
    id: 'byzantine-empire',
    name: 'Byzantine Empire',
    year: '330–1453 AD',
    region: 'Rome',
    emoji: '⚜️',
    description: 'Rome\'s eastern ghost endures a thousand years: Greek fire burns fleets, Justinian rebuilds law, and Constantinople gleams gold.',
  },
  {
    id: 'classical-athens',
    name: 'Classical Athens',
    year: '480–399 BC',
    region: 'Greece',
    emoji: '🎭',
    description: 'Socrates questions everything, Pericles builds the Parthenon, and democracy makes its first trembling steps above the agora.',
  },
  {
    id: 'alexander-the-great',
    name: 'Age of Alexander',
    year: '336–323 BC',
    region: 'Greece',
    emoji: '🌍',
    description: 'In thirteen years Alexander conquers Persia, Egypt, and India — an unstoppable force of genius and madness reshaping the world.',
  },
  {
    id: 'thermopylae',
    name: 'Battle of Thermopylae',
    year: '480 BC',
    region: 'Greece',
    emoji: '🛡️',
    description: 'Three hundred Spartans hold the Hot Gates while Persia\'s millions pour south — a last stand that echoes through all of history.',
  },
  {
    id: 'minoan-crete',
    name: 'Minoan Crete',
    year: '2700–1450 BC',
    region: 'Greece',
    emoji: '🐂',
    description: 'Bull-leapers somersault in palace courts, frescoes shimmer in ochre and lapis, and a sophisticated sea empire rules before Greece existed.',
  },
  {
    id: 'troy',
    name: 'Trojan War',
    year: '1200 BC',
    region: 'Greece',
    emoji: '🐴',
    description: 'A wooden horse waits outside Troy\'s walls: Achilles rages, Hector prays, Helen watches from the battlements as ten years end in fire.',
  },

  // EGYPT (5)
  {
    id: 'old-kingdom-egypt',
    name: 'Old Kingdom Egypt',
    year: '2686–2181 BC',
    region: 'Egypt',
    emoji: '🔺',
    description: 'Pyramid builders haul limestone under a merciless sun: the Pharaoh is living god, the Nile is life, and the afterlife is everything.',
  },
  {
    id: 'new-kingdom-egypt',
    name: 'New Kingdom Egypt',
    year: '1550–1070 BC',
    region: 'Egypt',
    emoji: '☀️',
    description: 'Ramesses II carves his face on every temple; chariots thunder across Nubia; Hatshepsut rules as king and history tries to erase her.',
  },
  {
    id: 'ptolemaic-egypt',
    name: 'Ptolemaic Egypt',
    year: '305–30 BC',
    region: 'Egypt',
    emoji: '📜',
    description: 'Greek pharaohs rule Egyptian gods: the Library of Alexandria gathers all human knowledge while scholars debate the size of the earth.',
  },
  {
    id: 'cleopatra-egypt',
    name: 'Cleopatra\'s Egypt',
    year: '51–30 BC',
    region: 'Egypt',
    emoji: '👑',
    description: 'Rome circles like a vulture: Cleopatra speaks nine languages, seduces Caesar and Antony, and fights to save a dying kingdom\'s soul.',
  },
  {
    id: 'amarna-egypt',
    name: 'Amarna Period',
    year: '1353–1336 BC',
    region: 'Egypt',
    emoji: '🌅',
    description: 'Akhenaten shatters a thousand years of religion — one sun god, a new city, and a queen named Nefertiti whose beauty defies time.',
  },

  // VIKINGS (5)
  {
    id: 'viking-age',
    name: 'Viking Age',
    year: '793–1066',
    region: 'Scandinavia',
    emoji: '⚓',
    description: 'Longships emerge from fog: raiders become traders, settlers, and explorers who touch America\'s shore while Europe\'s monasteries tremble.',
  },
  {
    id: 'norse-exploration',
    name: 'Norse Exploration',
    year: '870–1000',
    region: 'Scandinavia',
    emoji: '🗺️',
    description: 'Leif Erikson follows rumor west; Iceland and Greenland settled; the Atlantic crossed in open boats by men who laughed at death.',
  },
  {
    id: 'althing',
    name: 'Icelandic Althing',
    year: '930–1262',
    region: 'Iceland',
    emoji: '⚖️',
    description: 'The world\'s oldest parliament meets on volcanic plains: sagas are recited, blood feuds arbitrated, and democracy survives at the edge of ice.',
  },
  {
    id: 'varangian-guard',
    name: 'Varangian Guard',
    year: '988–1204',
    region: 'Byzantium',
    emoji: '🪓',
    description: 'Norse warriors serve the Byzantine emperor as elite axe-guards: riches flow north, Orthodox faith follows south, cultures collide magnificently.',
  },
  {
    id: 'age-of-ragnar',
    name: 'Age of Ragnar',
    year: '845–900',
    region: 'Scandinavia',
    emoji: '🐍',
    description: 'Ragnar Lothbrok and sons raid Paris, besiege Winchester, and plant the Raven Banner in soil from England to the Mediterranean.',
  },

  // MEDIEVAL EUROPE (11)
  {
    id: 'black-death',
    name: 'Black Death Europe',
    year: '1347–1353',
    region: 'Europe',
    emoji: '💀',
    description: 'One third of Europe dies in five years: plague doctors in beak masks walk empty streets, flagellants beat themselves bloody, and the old order shatters.',
  },
  {
    id: 'crusades',
    name: 'The Crusades',
    year: '1096–1291',
    region: 'Middle East',
    emoji: '✝️',
    description: 'Pope Urban\'s call echoes from France to Jerusalem: knights, peasants, and children march into desert heat armed with faith and iron.',
  },
  {
    id: 'joan-of-arc',
    name: 'Joan of Arc\'s France',
    year: '1429–1431',
    region: 'France',
    emoji: '⚔️',
    description: 'A teenage farm girl hears angel voices, leads armies, and drives the English from Orleans — then burns at Rouen while France watches.',
  },
  {
    id: 'norman-conquest',
    name: 'Norman Conquest',
    year: '1066',
    region: 'England',
    emoji: '🏰',
    description: 'William the Bastard crosses the Channel: Harold falls at Hastings with an arrow, and England\'s language, law, and blood transform forever.',
  },
  {
    id: 'magna-carta',
    name: 'Magna Carta England',
    year: '1215',
    region: 'England',
    emoji: '📜',
    description: 'Barons force King John to kneel at Runnymede — a parchment limits royal power for the first time and plants the seed of all future rights.',
  },
  {
    id: 'holy-roman-empire',
    name: 'Holy Roman Empire',
    year: '962–1250',
    region: 'Central Europe',
    emoji: '👑',
    description: 'Neither holy, Roman, nor an empire — a patchwork of German princes, Italian cities, and papal politics in perpetual creative chaos.',
  },
  {
    id: 'hanseatic-league',
    name: 'Hanseatic League',
    year: '1241–1669',
    region: 'Northern Europe',
    emoji: '⚓',
    description: 'German merchant cities form a trading empire without armies: herring, cloth, and amber flow through northern ports that answer to no king.',
  },
  {
    id: 'wars-of-roses',
    name: 'Wars of the Roses',
    year: '1455–1485',
    region: 'England',
    emoji: '🌹',
    description: 'York versus Lancaster in a dynastic bloodbath: cousins kill cousins for the English throne until a Tudor rose ends thirty years of red.',
  },
  {
    id: 'charlemagne',
    name: 'Charlemagne\'s Empire',
    year: '768–814',
    region: 'Europe',
    emoji: '⚔️',
    description: 'A Frankish king unites Europe\'s ruins by sword and scripture: schools open, laws written, and for a moment, Rome\'s ghost walks again.',
  },
  {
    id: 'knights-templar',
    name: 'Knights Templar',
    year: '1119–1312',
    region: 'Middle East',
    emoji: '✝️',
    description: 'Warrior monks guard pilgrims, invent banking, and accumulate such power that a French king destroys them all in one terrifying Friday.',
  },
  {
    id: 'fourth-crusade',
    name: 'Fourth Crusade',
    year: '1202–1204',
    region: 'Constantinople',
    emoji: '💰',
    description: 'Crusaders meant for Jerusalem end up sacking Constantinople instead — Venetian merchants profit, Christian kills Christian, the East is never forgiven.',
  },

  // OTTOMAN & PERSIA (7)
  {
    id: 'ottoman-golden-age',
    name: 'Ottoman Golden Age',
    year: '1520–1566',
    region: 'Ottoman Empire',
    emoji: '🌙',
    description: 'Suleiman the Magnificent rules from Vienna\'s gates to Persia\'s border: the law, architecture, and poetry of his court dazzle three continents.',
  },
  {
    id: 'constantinople-falls',
    name: 'Fall of Constantinople',
    year: '1453',
    region: 'Ottoman Empire',
    emoji: '💥',
    description: 'Mehmed II\'s cannons shatter walls that held a thousand years: the last Byzantine emperor dies in the breach and a new world begins.',
  },
  {
    id: 'achaemenid-persia',
    name: 'Achaemenid Persian Empire',
    year: '550–330 BC',
    region: 'Persia',
    emoji: '🦁',
    description: 'Cyrus the Great frees peoples instead of enslaving them; Darius builds roads; Xerxes crosses the Hellespont on a bridge of boats.',
  },
  {
    id: 'sassanid-persia',
    name: 'Sassanid Persian Empire',
    year: '224–651 AD',
    region: 'Persia',
    emoji: '🔥',
    description: 'Persia\'s last native empire: Zoroastrian fire temples glow, silk weaving reaches perfection, and Rome is humiliated at Edessa.',
  },
  {
    id: 'islamic-golden-age',
    name: 'Islamic Golden Age',
    year: '786–1258',
    region: 'Middle East',
    emoji: '⭐',
    description: 'Baghdad\'s House of Wisdom gathers the world\'s knowledge: algebra invented, stars named, surgery advanced while Europe gropes in darkness.',
  },
  {
    id: 'safavid-persia',
    name: 'Safavid Persia',
    year: '1501–1736',
    region: 'Persia',
    emoji: '🕌',
    description: 'Shah Abbas rebuilds Isfahan into the world\'s most beautiful city while war with Ottoman Turkey defines a religious fault line still burning.',
  },
  {
    id: 'abbasid-caliphate',
    name: 'Abbasid Caliphate',
    year: '750–1258',
    region: 'Middle East',
    emoji: '📚',
    description: 'The caliphate at its height: One Thousand and One Nights composed in Baghdad\'s gardens while philosophers reconcile Aristotle with the Quran.',
  },

  // MONGOL (4)
  {
    id: 'mongol-conquest',
    name: 'Mongol Conquest',
    year: '1206–1259',
    region: 'Eurasia',
    emoji: '🐎',
    description: 'Genghis Khan unites the steppe tribes and unleashes the greatest military machine the world has seen — cities that resist are dust.',
  },
  {
    id: 'pax-mongolica',
    name: 'Pax Mongolica',
    year: '1260–1360',
    region: 'Eurasia',
    emoji: '🛤️',
    description: 'The Mongol peace: trade flows from China to France in safety, plague travels the same roads, and Marco Polo walks to Kublai Khan\'s court.',
  },
  {
    id: 'timur',
    name: 'Age of Timur',
    year: '1370–1405',
    region: 'Central Asia',
    emoji: '💀',
    description: 'Tamerlane the Lame conquers from India to Turkey, builds towers of skulls, then dies on the road to China leaving Samarkand\'s turquoise domes.',
  },
  {
    id: 'golden-horde',
    name: 'Golden Horde',
    year: '1242–1502',
    region: 'Russia',
    emoji: '🏕️',
    description: 'Mongol khans tax Russia from the steppe: Russian princes kneel in the horde\'s golden tent, Batu\'s cavalry haunts European nightmares.',
  },

  // AMERICAS (7)
  {
    id: 'aztec-empire',
    name: 'Aztec Empire',
    year: '1428–1521',
    region: 'Mesoamerica',
    emoji: '🦅',
    description: 'Tenochtitlan floats on a lake, larger than any European city: priests cut hearts for the sun, warriors wear jaguar skins, and flowers bloom everywhere.',
  },
  {
    id: 'inca-empire',
    name: 'Inca Empire',
    year: '1438–1533',
    region: 'South America',
    emoji: '🦙',
    description: 'An empire without writing rules the Andes through quipu knots and roads: terraced mountains feed millions while the Sapa Inca is living sun.',
  },
  {
    id: 'maya-classic',
    name: 'Classic Maya',
    year: '250–900 AD',
    region: 'Mesoamerica',
    emoji: '🌿',
    description: 'City-states in the jungle: astronomers calculate Venus cycles, kings play the sacred ball game, and stelae record everything in glyph and stone.',
  },
  {
    id: 'olmec',
    name: 'Olmec Civilization',
    year: '1500–400 BC',
    region: 'Mesoamerica',
    emoji: '🗿',
    description: 'Mother culture of all Mesoamerica: colossal stone heads face the jungle, chocolate is first consumed, and the number zero stirs in priestly minds.',
  },
  {
    id: 'cahokia',
    name: 'Cahokia',
    year: '600–1400 AD',
    region: 'North America',
    emoji: '🌽',
    description: 'At the Mississippi\'s confluence stands a city larger than medieval London: massive earthen mounds, a woodhenge, and a civilization history forgot.',
  },
  {
    id: 'pueblo-peoples',
    name: 'Ancestral Pueblo',
    year: '700–1300 AD',
    region: 'North America',
    emoji: '🏜️',
    description: 'Multi-story cliff cities carved into canyon walls: turquoise traded to Mexico, ceremonies align with stars, drought will end everything.',
  },
  {
    id: 'mayan-collapse',
    name: 'Mayan Collapse',
    year: '800–1000 AD',
    region: 'Mesoamerica',
    emoji: '🌑',
    description: 'Great cities emptied in two centuries: drought, warfare, and elite excess topple the Classic Maya while their successors retreat north.',
  },

  // AGE OF EXPLORATION (8)
  {
    id: 'golden-age-piracy',
    name: 'Golden Age of Piracy',
    year: '1680–1730',
    region: 'Caribbean',
    emoji: '🏴‍☠️',
    description: 'Blackbeard blockades Charleston, Calico Jack sails with Anne Bonny, and Nassau becomes a pirate republic while merchants pray for convoy.',
  },
  {
    id: 'conquistadors',
    name: 'Spanish Conquistadors',
    year: '1492–1600',
    region: 'Americas',
    emoji: '⚔️',
    description: 'Cortés burns his ships and marches to Tenochtitlan; Pizarro strangles the Inca emperor; diseases do what armies cannot — empires fall in years.',
  },
  {
    id: 'magellan',
    name: 'Magellan\'s Circumnavigation',
    year: '1519–1522',
    region: 'Global',
    emoji: '🌏',
    description: 'Five ships leave Seville to circle the world — only one returns. Magellan dies in the Philippines and the planet\'s true size is finally known.',
  },
  {
    id: 'east-india-company',
    name: 'East India Company',
    year: '1600–1757',
    region: 'South Asia',
    emoji: '💰',
    description: 'A corporation with its own army: English merchants muscle into the spice trade, bribe nawabs, and slowly swallow an entire subcontinent.',
  },
  {
    id: 'portuguese-spice-route',
    name: 'Portuguese Spice Route',
    year: '1498–1580',
    region: 'Indian Ocean',
    emoji: '🌶️',
    description: 'Vasco da Gama rounds Africa and breaks the Ottoman spice monopoly: Lisbon grows rich, the Indian Ocean becomes a Portuguese lake.',
  },
  {
    id: 'dutch-golden-age',
    name: 'Dutch Golden Age',
    year: '1588–1672',
    region: 'Netherlands',
    emoji: '🌷',
    description: 'Tiny Holland rules global trade: tulip mania inflates and crashes, Rembrandt paints in Amsterdam, and Dutch fleets challenge Spain, Portugal, and England.',
  },
  {
    id: 'barbary-corsairs',
    name: 'Barbary Corsairs',
    year: '1500–1800',
    region: 'North Africa',
    emoji: '🏴‍☠️',
    description: 'North African pirates raid from Iceland to West Africa, holding a million Europeans as slaves while Ottoman sultans smile and collect tribute.',
  },
  {
    id: 'buccaneers',
    name: 'Buccaneers of Tortuga',
    year: '1640–1690',
    region: 'Caribbean',
    emoji: '🍖',
    description: 'Castaways and hunters become pirates on Hispaniola\'s north shore: Henry Morgan sacks Panama City and drinks himself to a knighthood.',
  },

  // RENAISSANCE & REVOLUTION (10)
  {
    id: 'italian-renaissance',
    name: 'Italian Renaissance',
    year: '1350–1600',
    region: 'Italy',
    emoji: '🎨',
    description: 'Florence under Medici gold: Leonardo sketches flying machines, Michelangelo argues with the Pope, and ancient Greece reborn reshapes humanity\'s self-image.',
  },
  {
    id: 'reformation',
    name: 'Protestant Reformation',
    year: '1517–1648',
    region: 'Europe',
    emoji: '📜',
    description: 'Luther nails 95 theses to a church door and Europe explodes: wars of religion, burning heretics, and the printing press makes faith everyone\'s business.',
  },
  {
    id: 'scientific-revolution',
    name: 'Scientific Revolution',
    year: '1543–1687',
    region: 'Europe',
    emoji: '🔭',
    description: 'Copernicus removes Earth from the center, Galileo peers through a telescope at moons, Newton sits under the apple tree — the world changes shape.',
  },
  {
    id: 'enlightenment',
    name: 'The Enlightenment',
    year: '1685–1789',
    region: 'Europe',
    emoji: '💡',
    description: 'Voltaire mocks kings, Rousseau romanticizes nature, and coffee houses buzz with dangerous questions about reason, liberty, and the divine right of rulers.',
  },
  {
    id: 'elizabethan-england',
    name: 'Elizabethan England',
    year: '1558–1603',
    region: 'England',
    emoji: '🎭',
    description: 'The Virgin Queen defies a Spanish Armada: Shakespeare writes in the Globe\'s shadow, Francis Drake circles the world, and England\'s golden age begins.',
  },
  {
    id: 'french-revolution',
    name: 'French Revolution',
    year: '1789–1799',
    region: 'France',
    emoji: '🔴',
    description: 'Liberty, equality, fraternity — and the guillotine: the Bastille falls, the king loses his head, and the Terror proves ideals have a price.',
  },
  {
    id: 'american-revolution',
    name: 'American Revolution',
    year: '1775–1783',
    region: 'North America',
    emoji: '🦅',
    description: 'Colonists in arms against the world\'s greatest empire: Valley Forge freezes Washington\'s men, Ben Franklin charms France, and a new nation is born.',
  },
  {
    id: 'haitian-revolution',
    name: 'Haitian Revolution',
    year: '1791–1804',
    region: 'Caribbean',
    emoji: '🔥',
    description: 'The only successful slave revolution in history: Toussaint L\'Ouverture outgenerals Napoleon, and the first Black republic rises from sugarcane and fire.',
  },
  {
    id: 'napoleonic-era',
    name: 'Napoleonic Europe',
    year: '1799–1815',
    region: 'Europe',
    emoji: '👑',
    description: 'A Corsican artillery officer crowns himself Emperor and conquers Europe: Moscow burns, Waterloo waits, and the world is remapped in his wake.',
  },
  {
    id: 'industrial-revolution',
    name: 'Industrial Revolution',
    year: '1760–1840',
    region: 'England',
    emoji: '⚙️',
    description: 'Children work looms in Manchester\'s mills, Watt\'s steam engine transforms everything, and humanity\'s relationship with work, time, and nature breaks forever.',
  },

  // AFRICA (8)
  {
    id: 'mali-empire',
    name: 'Mali Empire',
    year: '1235–1600',
    region: 'West Africa',
    emoji: '🌍',
    description: 'Mansa Musa\'s pilgrimage to Mecca collapses the gold price across North Africa and the Mediterranean — the richest man in history makes his mark.',
  },
  {
    id: 'songhai-empire',
    name: 'Songhai Empire',
    year: '1464–1591',
    region: 'West Africa',
    emoji: '📚',
    description: 'Timbuktu houses the largest library outside China: salt, gold, and slaves flow through Saharan routes while Askia Mohammad builds an empire of law.',
  },
  {
    id: 'great-zimbabwe',
    name: 'Great Zimbabwe',
    year: '1100–1450',
    region: 'Southern Africa',
    emoji: '🗿',
    description: 'Massive dry-stone towers rise without mortar in the African interior: gold and ivory traded to the Swahili coast, a kingdom European scholars refused to credit.',
  },
  {
    id: 'zulu-kingdom',
    name: 'Zulu Kingdom',
    year: '1816–1879',
    region: 'Southern Africa',
    emoji: '🛡️',
    description: 'Shaka Zulu invents revolutionary warfare and builds an empire: the bullhorn formation, the iklwa short spear, and a military culture that stuns the British.',
  },
  {
    id: 'aksum-empire',
    name: 'Aksumite Empire',
    year: '100–940 AD',
    region: 'East Africa',
    emoji: '⛪',
    description: 'Ethiopia\'s ancient empire trades with Rome and India: obelisks pierce the sky, Christianity adopted before most of Europe, and the Ark of the Covenant hides nearby.',
  },
  {
    id: 'carthage',
    name: 'Carthaginian Empire',
    year: '814–146 BC',
    region: 'North Africa',
    emoji: '🐘',
    description: 'Hannibal marches elephants over the Alps and breaks Roman armies: Carthage rules the western Mediterranean until Rome burns it to the salt-cursed ground.',
  },
  {
    id: 'kingdom-of-kush',
    name: 'Kingdom of Kush',
    year: '1070 BC–350 AD',
    region: 'Northeast Africa',
    emoji: '🔺',
    description: 'Black pharaohs from Nubia conquer Egypt and rule as the 25th Dynasty: Meroe\'s iron smelters feed an empire while pyramids cluster in the desert.',
  },
  {
    id: 'swahili-coast',
    name: 'Swahili Coast',
    year: '900–1500 AD',
    region: 'East Africa',
    emoji: '🌊',
    description: 'Monsoon winds carry dhows between Africa, Arabia, and India: stone cities grow rich on gold and ivory, a hybrid language fuses Bantu and Arabic.',
  },

  // INDIA (7)
  {
    id: 'maurya-empire',
    name: 'Mauryan Empire',
    year: '322–185 BC',
    region: 'India',
    emoji: '🦁',
    description: 'Chandragupta unites India, Ashoka converts to Buddhism after Kalinga\'s slaughter and inscribes mercy on rock faces across a subcontinent.',
  },
  {
    id: 'gupta-empire',
    name: 'Gupta Golden Age',
    year: '320–550 AD',
    region: 'India',
    emoji: '🌺',
    description: 'India\'s classical peak: zero invented, Kalidasa writes poetry, Aryabhata calculates the Earth\'s circumference, medicine and astronomy flourish together.',
  },
  {
    id: 'mughal-empire',
    name: 'Mughal Empire',
    year: '1526–1707',
    region: 'India',
    emoji: '🕌',
    description: 'Akbar the Great rules with religious tolerance; the Taj Mahal rises as a monument to love; Aurangzeb\'s wars exhaust an empire that once seemed eternal.',
  },
  {
    id: 'maratha-empire',
    name: 'Maratha Empire',
    year: '1674–1818',
    region: 'India',
    emoji: '⚔️',
    description: 'Shivaji defies the Mughal emperor with guerrilla warfare: a Hindu kingdom rises in the Deccan and eventually controls most of the subcontinent.',
  },
  {
    id: 'vijayanagara',
    name: 'Vijayanagara Empire',
    year: '1336–1646',
    region: 'India',
    emoji: '🏛️',
    description: 'The last great Hindu empire of the south: Hampi\'s bazaars sell diamonds by the pound, temple towers scrape heaven, and Persian visitors write in awe.',
  },
  {
    id: 'indus-valley',
    name: 'Indus Valley Civilization',
    year: '2600–1900 BC',
    region: 'South Asia',
    emoji: '🏙️',
    description: 'Mohenjo-daro has indoor plumbing while Rome\'s hills are mud huts: a planned civilization of 50,000 people that history has yet to fully decipher.',
  },
  {
    id: 'chola-dynasty',
    name: 'Chola Dynasty',
    year: '848–1279 AD',
    region: 'South India',
    emoji: '🌊',
    description: 'Tamil naval empire that reaches Southeast Asia: the Brihadeeswarar temple defies gravity in stone, bronze Nataraja dancing flames are cast in perfection.',
  },

  // SOUTHEAST ASIA (5)
  {
    id: 'khmer-empire',
    name: 'Khmer Empire',
    year: '802–1431',
    region: 'Southeast Asia',
    emoji: '🛕',
    description: 'Angkor Wat rises from the Cambodian jungle — the largest religious monument ever built, center of a hydraulic empire that fed a million people.',
  },
  {
    id: 'majapahit',
    name: 'Majapahit Empire',
    year: '1293–1527',
    region: 'Java',
    emoji: '🌺',
    description: 'Java\'s golden empire spans to the Philippines: Gajah Mada\'s oath to unite the archipelago, trade in spices and silk, and magnificent Hindu-Buddhist art.',
  },
  {
    id: 'srivijaya',
    name: 'Srivijaya Empire',
    year: '650–1375',
    region: 'Sumatra',
    emoji: '⚓',
    description: 'Palembang controls the Malacca Strait for seven centuries: Buddhist pilgrims stop on the way to India, tribute flows in, and pepper makes kings rich.',
  },
  {
    id: 'ayutthaya',
    name: 'Kingdom of Ayutthaya',
    year: '1351–1767',
    region: 'Thailand',
    emoji: '🏛️',
    description: 'Gilded towers and elephants: Ayutthaya trades with China, Portugal, and Japan, hosts foreign embassies, and for four centuries rules a Southeast Asian empire.',
  },
  {
    id: 'pagan-empire',
    name: 'Pagan Empire',
    year: '849–1297',
    region: 'Myanmar',
    emoji: '🛕',
    description: 'Ten thousand pagodas cover the Irrawaddy plain: King Anawrahta unites Burma under Theravada Buddhism until Kublai Khan\'s ambassador loses his head.',
  },

  // MESOPOTAMIA (6)
  {
    id: 'sumerian',
    name: 'Sumerian Civilization',
    year: '4500–1900 BC',
    region: 'Mesopotamia',
    emoji: '📋',
    description: 'Writing invented in Uruk\'s counting houses: the Epic of Gilgamesh composed, ziggurats pierce the sky, and the first cities teach humanity how to be urban.',
  },
  {
    id: 'babylonian',
    name: 'Babylonian Empire',
    year: '1894–539 BC',
    region: 'Mesopotamia',
    emoji: '🌹',
    description: 'Hammurabi\'s code carves law in stone; Nebuchadnezzar\'s hanging gardens water the air; Babylon\'s ziggurat inspires a tower story that echoes forever.',
  },
  {
    id: 'assyrian-empire',
    name: 'Assyrian Empire',
    year: '911–609 BC',
    region: 'Mesopotamia',
    emoji: '⚔️',
    description: 'The ancient world\'s most feared army: Nineveh\'s great library collects all knowledge while iron-shod Assyrian infantry reduce cities to skulls and ash.',
  },
  {
    id: 'hittite',
    name: 'Hittite Empire',
    year: '1650–1180 BC',
    region: 'Anatolia',
    emoji: '🗡️',
    description: 'Masters of iron and chariot warfare: the Hittites fight Egypt to a standstill at Kadesh and sign history\'s first known peace treaty.',
  },
  {
    id: 'phoenician',
    name: 'Phoenician Civilization',
    year: '1500–300 BC',
    region: 'Levant',
    emoji: '⚓',
    description: 'Purple dye and the alphabet: Phoenician sailors circle Africa, found Carthage, and give Greece (and humanity) the letters you are reading right now.',
  },
  {
    id: 'neo-babylonian',
    name: 'Neo-Babylonian Empire',
    year: '626–539 BC',
    region: 'Mesopotamia',
    emoji: '🌙',
    description: 'Nebuchadnezzar sacks Jerusalem and builds Babylon into a wonder: Ishtar Gate gleams blue, Jewish exiles weep by the rivers, Cyrus waits in the east.',
  },

  // KOREA (3)
  {
    id: 'three-kingdoms-korea',
    name: 'Three Kingdoms Korea',
    year: '57 BC–668 AD',
    region: 'Korea',
    emoji: '⚔️',
    description: 'Goguryeo, Baekje, and Silla vie for the peninsula: Buddhist missionaries from China transform culture, Hwarang warrior youth shape a future kingdom.',
  },
  {
    id: 'joseon-dynasty',
    name: 'Joseon Dynasty Korea',
    year: '1392–1897',
    region: 'Korea',
    emoji: '📜',
    description: 'Neo-Confucian governance for five centuries: King Sejong creates Hangul alphabet for common people, turtle ships defeat Japan\'s navy under Yi Sun-sin.',
  },
  {
    id: 'goryeo-kingdom',
    name: 'Goryeo Kingdom',
    year: '918–1392',
    region: 'Korea',
    emoji: '🏺',
    description: 'Korea\'s medieval golden age: the first metal movable type invented, celadon pottery reaches peerless beauty, the Buddhist Tripitaka carved on 80,000 wooden blocks.',
  },

  // PACIFIC (3)
  {
    id: 'polynesian-voyagers',
    name: 'Polynesian Voyagers',
    year: '1000 BC–1300 AD',
    region: 'Pacific Ocean',
    emoji: '🌊',
    description: 'Without compass or chart, Polynesian navigators read stars, waves, and birds to settle every habitable island across the vast Pacific over two millennia.',
  },
  {
    id: 'hawaiian-kingdoms',
    name: 'Hawaiian Kingdoms',
    year: '1300–1810',
    region: 'Hawaii',
    emoji: '🌺',
    description: 'Chiefs wage war with feather cloaks and volcanic courage: surfing a royal sport, hula preserves history in movement, and Cook\'s arrival ends an age.',
  },
  {
    id: 'maori-aotearoa',
    name: 'Maori Aotearoa',
    year: '1300–1840',
    region: 'New Zealand',
    emoji: '🌿',
    description: 'The last great land found by humans: Maori carve the world\'s most complex tattoos, build hilltop pa fortresses, and haka shakes the ground.',
  },

  // SPECIAL & FASCINATING (50+)
  {
    id: 'spartan-agoge',
    name: 'Spartan Agoge',
    year: '600–371 BC',
    region: 'Sparta',
    emoji: '🛡️',
    description: 'Boys stolen at seven and forged into the ancient world\'s most feared warriors through starvation, beatings, and the art of killing without mercy.',
  },
  {
    id: 'pompeii-before-vesuvius',
    name: 'Pompeii Before Vesuvius',
    year: '79 AD',
    region: 'Rome',
    emoji: '🌋',
    description: 'The mountain smokes but the wine is good: graffiti on every wall, elections argued, gladiators famous as pop stars — the last perfect Roman summer.',
  },
  {
    id: 'library-of-alexandria',
    name: 'Library of Alexandria',
    year: '300 BC–400 AD',
    region: 'Egypt',
    emoji: '📚',
    description: 'Every ship docking at Alexandria must surrender its scrolls to be copied: the world\'s knowledge assembled in one place — fire will take it all.',
  },
  {
    id: 'moorish-andalusia',
    name: 'Moorish Andalusia',
    year: '711–1492',
    region: 'Spain',
    emoji: '🕌',
    description: 'Muslim, Jewish, and Christian scholars work side by side in Córdoba: the Alhambra rises in geometric perfection above a city that lights its streets at night.',
  },
  {
    id: 'crusader-states',
    name: 'Crusader States',
    year: '1099–1291',
    region: 'Holy Land',
    emoji: '✝️',
    description: 'Frankish knights build castles in Syrian heat, trade silk in Acre\'s bazaars, and slowly go native as Saladin waits patiently to reclaim Jerusalem.',
  },
  {
    id: 'scythian-steppe',
    name: 'Scythian Steppe',
    year: '700–200 BC',
    region: 'Central Asia',
    emoji: '🏹',
    description: 'Horse-archer nomads of the Eurasian steppe: golden torques, cannabis-fueled funeral rites, and women who fight from horseback from the Danube to Mongolia.',
  },
  {
    id: 'tibetan-empire',
    name: 'Tibetan Empire',
    year: '618–842 AD',
    region: 'Tibet',
    emoji: '🏔️',
    description: 'Roof-of-the-world empire that once raided Tang China: Buddhism introduced by princess brides, sky burials beneath circling vultures, and an army of mountain men.',
  },
  {
    id: 'byzantine-intrigue',
    name: 'Byzantine Court Intrigue',
    year: '600–1200 AD',
    region: 'Constantinople',
    emoji: '🗡️',
    description: 'Eunuchs, empresses, and poisoned wine: the Byzantine court where six emperors were blinded in thirty years and Theodora rises from actress to Augusta.',
  },
  {
    id: 'celtic-britain',
    name: 'Celtic Britain',
    year: '400 BC–43 AD',
    region: 'Britain',
    emoji: '🌿',
    description: 'Druids in sacred groves memorize a thousand years of law; Boudicca burns Roman Londinium to ash; iron-age hillforts look down on painted warriors.',
  },
  {
    id: 'viking-dublin',
    name: 'Viking Dublin',
    year: '841–1014 AD',
    region: 'Ireland',
    emoji: '⚓',
    description: 'Norse raiders become settlers: Dublin founded as a slave market, Irish monks copied and fought, and Brian Boru finally breaks the Viking grip at Clontarf.',
  },
  {
    id: 'ottoman-vs-safavid',
    name: 'Ottoman vs Safavid Wars',
    year: '1514–1639',
    region: 'Middle East',
    emoji: '⚔️',
    description: 'Sunni versus Shia becomes the century\'s great conflict: Selim I defeats the Safavids at Chaldiran, eastern Anatolia burns, and the schism deepens forever.',
  },
  {
    id: 'mughal-durbar',
    name: 'Mughal Durbar',
    year: '1605–1658',
    region: 'India',
    emoji: '👑',
    description: 'Jahangir\'s court weighs the emperor in gold, Nur Jahan effectively rules, miniature painters capture every peacock feather — Mughal magnificence at its height.',
  },
  {
    id: 'haitian-free-state',
    name: 'Haitian Free State',
    year: '1804–1825',
    region: 'Caribbean',
    emoji: '🔥',
    description: 'First Black republic in the world: Jean-Jacques Dessalines declares independence after defeating Napoleon\'s army, a beacon and a threat to every slave society.',
  },
  {
    id: 'roman-gladiators',
    name: 'Roman Gladiatorial Games',
    year: '100 BC–400 AD',
    region: 'Rome',
    emoji: '🗡️',
    description: 'The arena is politics by other means: emperors buy votes with blood, gladiators become celebrities, and the roar of 50,000 Romans is the loudest sound on earth.',
  },
  {
    id: 'ancient-trade-routes',
    name: 'Silk Road Crossroads',
    year: '100–600 AD',
    region: 'Central Asia',
    emoji: '🐪',
    description: 'Samarkand and Merv where Rome meets China: plague travels with silk, Buddhism rides with merchants, and a dozen languages are heard in any caravanserai.',
  },
  {
    id: 'spanish-inquisition',
    name: 'Spanish Inquisition',
    year: '1478–1834',
    region: 'Spain',
    emoji: '🔥',
    description: 'Tomás de Torquemada ensures nobody expects the Inquisition: converted Jews and Muslims interrogated for hidden heresies as Spain\'s empire rises on blood and gold.',
  },
  {
    id: 'venetian-republic',
    name: 'Venetian Republic',
    year: '697–1797',
    region: 'Italy',
    emoji: '🎭',
    description: 'Built on water and trade: Venice\'s Council of Ten runs the world\'s most efficient spy network, the Doge elected for life, and Carnival hides every sin in masks.',
  },
  {
    id: 'shogun-tokugawa',
    name: 'Tokugawa Shogunate',
    year: '1603–1868',
    region: 'Japan',
    emoji: '🏯',
    description: 'Japan locked to the world behind sakoku: samurai become bureaucrats, kabuki replaces battles, and Edo grows into the world\'s largest city in enforced peace.',
  },
  {
    id: 'aztec-priests',
    name: 'Aztec Temple Rites',
    year: '1325–1521',
    region: 'Mesoamerica',
    emoji: '🌞',
    description: 'Obsidian blades reach into chests to feed the sun: priests at pyramid summits in bloodstained robes, eagle and jaguar warriors compete to fill the altars.',
  },
  {
    id: 'ancient-olympics',
    name: 'Ancient Olympics',
    year: '776 BC–393 AD',
    region: 'Greece',
    emoji: '🏅',
    description: 'Wars paused every four years for naked athletes at Olympia: chariot races, wrestling, the pankration — and statues of victors that outlive their cities.',
  },
  {
    id: 'roman-legions',
    name: 'Roman Legions on Campaign',
    year: '50 BC–100 AD',
    region: 'Rome',
    emoji: '🦅',
    description: `A Roman legion on the march: 5,000 men build a fortified camp every night, centurions' vine staffs crack across backs, and the eagle standard must never fall.`,
  },
  {
    id: 'ming-voyages',
    name: 'Zheng He\'s Great Voyages',
    year: '1405–1433',
    region: 'Indian Ocean',
    emoji: '⛵',
    description: 'Treasure fleets larger than any European armada sail to Arabia and Africa: giraffes brought back to Beijing, but then China turns inward forever.',
  },
  {
    id: 'medieval-pilgrimage',
    name: 'Medieval Pilgrimage Routes',
    year: '1000–1400',
    region: 'Europe',
    emoji: '✝️',
    description: 'Pilgrims walk the Camino to Santiago: miracle stories exchanged at inns, relics touch swollen limbs, and commerce thrives on holy feet pounding the earth.',
  },
  {
    id: 'mongol-horse-lords',
    name: 'Mongol Horse Lords',
    year: '1206–1227',
    region: 'Central Asia',
    emoji: '🐎',
    description: 'The Mongol kurultai names Temujin as Genghis Khan: the steppe trembles, cities that resist become warning stories, cities that submit are left in peace.',
  },
  {
    id: 'ancient-egypt-workers',
    name: 'Pyramid Builders',
    year: '2560 BC',
    region: 'Egypt',
    emoji: '🔺',
    description: 'Workers — not slaves — receive wages, medical care, and beer rations while dragging limestone blocks: a vast logistical miracle invisible beneath the silence.',
  },
  {
    id: 'greek-philosophers',
    name: 'Socratic Athens',
    year: '470–399 BC',
    region: 'Greece',
    emoji: '🏛️',
    description: 'Socrates interrogates everyone in the agora until Athens tries him for corrupting youth: Plato records everything, and the examined life begins its long argument.',
  },
  {
    id: 'age-of-sail',
    name: 'Age of Sail Navies',
    year: '1650–1815',
    region: 'Atlantic',
    emoji: '⚓',
    description: 'Triple-decked warships exchange broadsides until gun-decks fill with smoke and gore: promotion by death, press gangs fill the fleet, and Nelson falls at Trafalgar.',
  },
  {
    id: 'inca-roads',
    name: 'Inca Road Runners',
    year: '1438–1533',
    region: 'South America',
    emoji: '🦙',
    description: 'Chasqui relay runners sprint 250 miles a day carrying quipu messages across the Andes: the emperor eats fresh fish from the Pacific carried at altitude.',
  },
  {
    id: 'black-sea-trade',
    name: 'Black Sea Greek Colonies',
    year: '700–300 BC',
    region: 'Black Sea',
    emoji: '🌾',
    description: 'Greek cities dotting the Black Sea\'s shores trade grain for silver: Scythian gold flows south, Athenian pottery flows north, and cultures blur beautifully.',
  },
  {
    id: 'roman-britain',
    name: 'Roman Britain',
    year: '43–410 AD',
    region: 'Britain',
    emoji: '🏛️',
    description: 'Legions build Hadrian\'s Wall against the Picts: bathhouses steam in the English rain, Londinium grows rich, and native Britons learn to drink garum sauce.',
  },
  {
    id: 'medieval-knights',
    name: 'Age of Chivalry',
    year: '1100–1400',
    region: 'France',
    emoji: '🛡️',
    description: 'Tournaments, troubadours, and courtly love: knights ride for honor, ladies grant favors, and the code of chivalry creates beauty from organized violence.',
  },
  {
    id: 'ming-forbidden-city',
    name: 'Ming Forbidden City',
    year: '1420–1644',
    region: 'China',
    emoji: '🏯',
    description: 'A city within a city where the Emperor is Heaven\'s son: 9,000 rooms, eunuch intriguers, concubines in gilded cages, and a bureaucracy of terrifying complexity.',
  },
  {
    id: 'ancient-india-trade',
    name: 'Ancient Indian Ocean Trade',
    year: '100 BC–500 AD',
    region: 'Indian Ocean',
    emoji: '🌊',
    description: 'Roman gold flows to India for pepper and muslin: Tamil merchants set up colonies in Southeast Asia, monsoon winds are mapped, and spice routes made empires.',
  },
  {
    id: 'dutch-east-indies',
    name: 'Dutch East Indies',
    year: '1619–1799',
    region: 'Indonesia',
    emoji: '🌿',
    description: 'The VOC\'s Batavia controls the nutmeg trade through genocide and discipline: entire islands depopulated for profit as Dutch merchants grow the richest in the world.',
  },
  {
    id: 'roman-senate',
    name: 'Roman Senate',
    year: '200–44 BC',
    region: 'Rome',
    emoji: '🏛️',
    description: 'The Senate floor where Cicero denounces Catiline, Caesar is warned of the Ides, and Crassus brags about wealth while Pompey returns trailing glory.',
  },
  {
    id: 'aztec-market',
    name: 'Tlatelolco Market',
    year: '1400–1521',
    region: 'Mesoamerica',
    emoji: '🛒',
    description: 'The greatest market in the world: 60,000 traders daily, cacao money changing hands, live animals, luxury feathers, obsidian blades, and Spanish eyes go wide.',
  },
  {
    id: 'medieval-florence',
    name: 'Medieval Florence',
    year: '1300–1400',
    region: 'Italy',
    emoji: '🌸',
    description: 'Bankers invent letters of credit, the Pazzi conspire against the Medici in the cathedral, Dante writes exile into beauty — money and art entangled forever.',
  },
  {
    id: 'opium-war-china',
    name: 'Opium War China',
    year: '1839–1842',
    region: 'China',
    emoji: '⚔️',
    description: 'Britain forces China to buy opium with cannon: the Qing dynasty humiliated, Hong Kong ceded, a century of shame begins as the Celestial Empire cracks.',
  },
  {
    id: 'mesoamerican-ballgame',
    name: 'Sacred Ballgame',
    year: '1400 BC–1521 AD',
    region: 'Mesoamerica',
    emoji: '⚽',
    description: 'The rubber ball cannot touch the ground: players use hips and knees in life-or-death games, courts at every city, the loser (or winner?) feeds the gods.',
  },
  {
    id: 'silk-road-tang',
    name: 'Tang Silk Road',
    year: '618–907 AD',
    region: 'Central Asia',
    emoji: '🐪',
    description: 'Chang\'an\'s western markets sell Iranian silk, Sogdian wine, and Central Asian musicians: foreigners welcomed, Buddhism and Islam trading doctrine alongside goods.',
  },
  {
    id: 'ming-sea-ban',
    name: 'Chinese Sea Ban Era',
    year: '1371–1567',
    region: 'China',
    emoji: '🚢',
    description: 'China bans all foreign trade and retreats behind its walls: smugglers get rich, coastal villages starved, and the greatest navy in history is burned by its own emperor.',
  },
  {
    id: 'atlantic-slave-trade',
    name: 'Atlantic Slave Trade',
    year: '1500–1800',
    region: 'Atlantic',
    emoji: '⛓️',
    description: 'Twelve million people taken from Africa in iron chains: the triangle trade builds European wealth and American plantations on bottomless cruelty and stolen lives.',
  },
  {
    id: 'reformation-germany',
    name: 'Reformation Germany',
    year: '1517–1555',
    region: 'Germany',
    emoji: '📜',
    description: 'Peasants revolt believing Luther\'s freedom is social; Anabaptists drown by the dozens in rivers; the printing press makes martyrs and pamphlets interchangeable.',
  },
  {
    id: 'renaissance-venice',
    name: 'Renaissance Venice',
    year: '1400–1600',
    region: 'Italy',
    emoji: '🎭',
    description: 'The Serenissima at its height: Titian paints in a city built on mud and magic, merchants plot over wine, the inquisitors watch from three-eyed masks at Carnival.',
  },
  {
    id: 'ancient-greece-persian-wars',
    name: 'Greco-Persian Wars',
    year: '499–449 BC',
    region: 'Greece',
    emoji: '⚔️',
    description: 'Marathon, Salamis, Plataea — Persian fire meets Greek bronze in the battles that decided whether the West would be Eastern: Themistocles reads the sea.',
  },
  {
    id: 'mughal-akbar',
    name: 'Akbar\'s Reign',
    year: '1556–1605',
    region: 'India',
    emoji: '👑',
    description: 'The Great Mughal who cannot read holds court with Hindu, Jain, Sufi, and Jesuit theologians: tolerance as policy, a new religion called Din-i-Ilahi, and an empire at peace.',
  },
  {
    id: 'inca-last-days',
    name: 'Last Days of the Inca',
    year: '1532–1572',
    region: 'South America',
    emoji: '🦙',
    description: 'Pizarro and 168 men capture Atahualpa in his litter: a room filled to the ceiling with gold does not save the emperor, and the Andes weep silver tears.',
  },
  {
    id: 'hundred-years-war',
    name: 'Hundred Years\' War',
    year: '1337–1453',
    region: 'France',
    emoji: '🏹',
    description: 'English longbows shred French chivalry at Crécy and Agincourt: the Black Prince burns his way through France while a peasant girl hears angels at Domrémy.',
  },
  {
    id: 'colonial-boston',
    name: 'Colonial Boston',
    year: '1763–1776',
    region: 'North America',
    emoji: '🍵',
    description: 'Tea in the harbor, Sons of Liberty in taverns, redcoats on the Common: a city winding itself toward revolution, one pamphlet and one midnight ride at a time.',
  },
  {
    id: 'ancient-carthage',
    name: 'Punic War Era',
    year: '264–146 BC',
    region: 'Mediterranean',
    emoji: '⚓',
    description: 'Carthage against Rome for Mediterranean supremacy: three wars in a century, Hannibal\'s impossible crossing of the Alps, and Scipio\'s burning of a civilization.',
  },
  {
    id: 'korean-joseon-court',
    name: 'Joseon Royal Court',
    year: '1392–1600',
    region: 'Korea',
    emoji: '📜',
    description: 'Neo-Confucian bureaucrats memorize the classics for examinations: factional struggles between literati and warriors, celadon turns to white porcelain, and the alphabet democratizes literacy.',
  },
  {
    id: 'ottoman-janissaries',
    name: 'Ottoman Janissaries',
    year: '1380–1826',
    region: 'Ottoman Empire',
    emoji: '🪖',
    description: 'Christian boys taken by devshirme and raised as the Sultan\'s elite slave-soldiers: they topple sultans who displease them and make Istanbul tremble.',
  },
  {
    id: 'mughal-taj-construction',
    name: 'Building the Taj Mahal',
    year: '1631–1653',
    region: 'India',
    emoji: '🕌',
    description: 'Shah Jahan drowns in grief for Mumtaz: 20,000 workers labor twenty years to build a perfect white marble tomb while the Mughal treasury drains toward ruin.',
  },
  {
    id: 'renaissance-papacy',
    name: 'Renaissance Papacy',
    year: '1447–1527',
    region: 'Rome',
    emoji: '⛪',
    description: 'Popes commission Michelangelo and fund armies: Alexander VI has children by his mistress, Julius II wears armor, and the Vatican becomes the world\'s most corrupt court.',
  },
  {
    id: 'mali-hajj',
    name: 'Mansa Musa\'s Hajj',
    year: '1324–1325',
    region: 'North Africa',
    emoji: '🌍',
    description: 'The Mali emperor\'s pilgrimage: 60,000 attendants, 500 slaves each carrying a golden staff, and so much gold distributed in Cairo that the price collapses for a decade.',
  },
  {
    id: 'inca-mita',
    name: 'Inca Labor State',
    year: '1438–1533',
    region: 'South America',
    emoji: '🏔️',
    description: 'No money, no markets, no merchants: the Inca mita system demands labor in lieu of tax, feeding all from royal storehouses while roads and temples rise from communal hands.',
  },
]

export function getEraById(id: string): Era | undefined {
  return ERAS.find((e) => e.id === id)
}
